### ISSUE TITLE
New 2.7.5 update.

### ISSUE THREAD

**Issue by RayJW** [flathub/org.upscayl.Upscayl#3]
Update the Flatpak to the new 2.7.5 version recently released. Maybe it would also make sense to add an external data checker so pull requests can be opened automatically on an update.

**Comment by NayamAmarshe** [comment]
I actually didn't release it on purpose because 2.8 will release tomorrow and 2.7.5 has some bugs.

**Comment by RayJW** [comment]
Oh, that makes sense. Thank you for your work! :)

**Comment by RayJW** [comment]
Update released :)
