### ISSUE TITLE
Enable Wayland support by default.

### ISSUE THREAD

**Issue by RayJW** [flathub/org.upscayl.Upscayl#8]
Since Upscayl always seems to use pretty up-to-date Electron versions, Wayland support is pretty solid and would greatly increase usability on Wayland systems. I think it's especially ironic, that the application is blurry on HiDPI displays, which is exactly the kind of problem this application wants to fix in a way.

The usual way to do this would probably be to add a script that enables Wayland flags on Wayland systems, see [here](https://github.com/flathub/net.cozic.joplin_desktop/blob/master/net.cozic.joplin_desktop.yml) or [here](https://github.com/flathub/org.signal.Signal/blob/master/signal-desktop.sh), but since the Electron version is so recent I would recommend just enabling it for all systems right away but with the Electron flag `--ozone-platform-hint=auto` like [here](https://github.com/flathub/com.bitwarden.desktop/pull/99/files). That way it will always use the correct backend.

**Comment by NayamAmarshe** [comment]
Thanks for the reminder, I'll update the flatpak. I was thinking about fixing for Wayland today.

**Comment by RayJW** [comment]
Seems to be working great now! Thanks :)
